data:
  raw_dir: "raw_data/"
  processed_dir: "processed_data/"
  confidence_threshold: 700
  
features:
  use_go_propagation: true
  use_ic_features: true
  go_svd_components: 100
  use_sequence_features: true   
  amino_acids: ['A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V'] 
  use_graph_features: true      
  graph_features: ['degree', 'betweenness', 'closeness'] 
  scale_features: true          
  
model:
  type: "GraphSAGE"  # or "GAT"
  hidden_dim: 128
  embed_dim: 64
  dropout: 0.5
  predictor_type: "mlp"  
  
training:
  epochs: 100
  lr: 0.005
  patience: 10
  val_ratio: 0.1
  test_ratio: 0.15
  lr_scheduler: false 
  data_split_seed: 42      

evaluation:
  run_advanced_analysis: true
  novel_pred_threshold: 0.9      
  novel_pred_top_k: 20          
  
  module_analysis:
    method: 'kmeans'       # 'kmeans' or 'dbscan'
    k_range_max: 10             
    dbscan_eps: 0.5             
    dbscan_min_samples: 5       
  
  prediction_pattern_analysis:
    degree_percentile: 50       

experiment:
  name: "ppi_link_prediction_test"
  dir: "experiments/ppi_link_prediction_test"  
