data:
  raw_dir: "raw_data/"
  processed_dir: "processed_data/"
  confidence_threshold: 700
  
features:
  use_go_propagation: true
  use_ic_features: true
  go_svd_components: 100
  use_sequence_features: true   
  amino_acids: ['A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V'] 
  use_graph_features: true      
  graph_features: ['degree', 'betweenness', 'closeness'] 
  scale_features: true          
  
model:
  type: "GraphSAGE"  # or "GAT"
  hidden_dim: 128
  embed_dim: 64
  dropout: 0.5
  predictor_type: "mlp"  
  
training:
  epochs: 100
  lr: 0.005
  patience: 10
  val_ratio: 0.1
  test_ratio: 0.15
  lr_scheduler: false 
  
  # NEW: Separate seeds for different operations to ensure reproducibility
  data_split_seed: 42      # Seed for data splitting (CRITICAL for consistent train/val/test)
  model_seed: 123          # Seed for model initialization and training
  feature_seed: 456        # Seed for feature engineering (SVD, scaling, etc.)

# NEW: Evaluation configuration section
evaluation:
  run_advanced_analysis: true
  novel_pred_threshold: 0.9      # Threshold for novel link predictions
  novel_pred_top_k: 20          # Number of top predictions to report
  
  # Functional module analysis settings
  module_analysis:
    method: 'kmeans'            # 'kmeans' or 'dbscan'
    k_range_max: 10             # Maximum k for k-means search
    dbscan_eps: 0.5             # DBSCAN epsilon (if using DBSCAN)
    dbscan_min_samples: 5       # DBSCAN min samples (if using DBSCAN)
  
  # Prediction pattern analysis
  prediction_pattern_analysis:
    degree_percentile: 50       # Percentile to separate high/low degree nodes

experiment:
  name: "ppi_link_prediction_test"
  dir: "experiments/ppi_link_prediction_test"  # NEW: Explicit experiment directory

# NEW: Logging configuration (optional but recommended)
logging:
  level: "INFO"                 # DEBUG, INFO, WARNING, ERROR
  save_logs: true              # Save logs to file
  log_file: "experiment.log"   # Log file name (will be in experiment dir)