# Data Configuration
data:
  # STRING PPI network parameters
  string:
    species_id: 10090  # Mus musculus taxonomy ID
    score_threshold: 0.7  # Minimum combined score for interactions
    use_experimental_only: false  # Whether to restrict to experimental evidence
    binary_interactions: true  # Use binary (unweighted) interactions
    self_loops: false  # Include self-interactions

  # Protein complex reference data
  complexes:
    source: "CORUM"  # Source database for known complexes
    min_size: 5  # Minimum complex size to consider
    max_size: 20  # Maximum complex size to consider
    min_confidence: "high"  # Only use high-confidence complexes

  # Gene Ontology annotations
  go_terms:
    namespaces: ["molecular_function", "biological_process", "cellular_component"]
    evidence_codes: ["EXP", "IDA", "IPI", "IMP", "IGI", "IEP", "HTP", "HDA", "HMP", "HGI", "HEP"]
    exclude_iea: true  # Exclude electronically inferred annotations

  # Data splitting parameters
  train_test_split:
    test_size: 0.2
    validation_size: 0.1
    random_seed: 42
    stratify_by_size: true  # Stratify by complex size

# Feature Engineering
features:
  # Topological features
  topology:
    use_features:
      - "degree"
      - "clustering_coefficient"
      - "betweenness_centrality"
      - "eigenvector_centrality"
      - "pagerank"
    normalization: "min_max"  # Normalization method for numerical features
  
  # GO term features
  go_terms:
    embedding_method: "one_hot"  # Alternatives: "embedding", "pca"
    embedding_dim: 64  # Dimension for GO term embeddings
    min_term_frequency: 5  # Minimum frequency for GO terms to include
  
  # Feature combination
  combined:
    concatenate: true  # Whether to concatenate topology and GO features
    topology_weight: 0.5  # Weight for topology features in combined representation
    go_weight: 0.5  # Weight for GO features in combined representation

# Model Configuration
model:
  # GVAE architecture
  gvae:
    encoder_type: "GCN"  # Graph convolution type: GCN, GAT, GraphSAGE
    hidden_channels: [64, 32]  # Hidden layer dimensions
    latent_dim: 16  # Latent space dimension
    activation: "relu"  # Activation function
    dropout: 0.2  # Dropout rate
    use_batch_norm: true  # Whether to use batch normalization
    edge_prediction: "inner_product"  # Edge prediction method
  
  # Training parameters
  training:
    epochs: 200
    batch_size: 32
    learning_rate: 0.001
    weight_decay: 0.0001
    kl_weight: 0.1  # Weight for KL divergence term
    patience: 20  # Early stopping patience
    use_gpu: true  # Whether to use GPU for training
    random_seed: 42  # Random seed for reproducibility
    gradient_clip: 1.0  # Gradient clipping value

# Baseline Configuration
baseline:
  # Random subgraph sampling
  random_sampling:
    num_samples: 1000  # Number of random subgraphs to generate
    match_size_distribution: true  # Match size distribution of known complexes
    ensure_connectivity: true  # Ensure connected subgraphs

# Evaluation Configuration
evaluation:
  # Structural metrics
  structural:
    metrics:
      - "density"
      - "average_degree"
      - "clustering_coefficient"
      - "diameter"
      - "modularity"
    comparison_method: "distribution"  # How to compare metrics: distribution, mean, etc.
  
  # Biological metrics
  biological:
    go_enrichment:
      pvalue_threshold: 0.05  # P-value threshold for significance
      correction_method: "fdr_bh"  # Multiple testing correction
    functional_similarity:
      method: "jaccard"  # Method to compute functional similarity
  
  # Novelty assessment
  novelty:
    edge_novelty: true  # Assess novelty of generated edges
    subgraph_novelty: true  # Assess novelty of entire subgraphs
    similarity_threshold: 0.7  # Threshold to consider structures similar

# Visualization Configuration
visualization:
  # Network visualization
  network:
    layout: "force"  # Network layout algorithm
    node_size_property: "degree"  # Property to determine node size
    node_color_property: "community"  # Property for node coloring
    edge_width: 1.0  # Edge width
    show_labels: true  # Whether to show node labels
    max_nodes_to_label: 20  # Maximum number of nodes to label
  
  # Metric visualization
  metrics:
    plot_distributions: true  # Plot metric distributions
    comparison_plots: ["box", "violin"]  # Types of comparison plots
    use_radar_charts: true  # Use radar charts for multi-metric comparison
  
  # Output formats
  output:
    formats: ["png", "svg", "html"]  # Output formats for figures
    dpi: 300  # DPI for raster formats
    interactive: true  # Generate interactive visualizations where possible

# Logging Configuration
logging:
  level: "INFO"  # Logging level
  save_path: "logs/"  # Path to save logs
  log_frequency: 10  # Log every N epochs
  tensorboard: true  # Whether to use TensorBoard